name: 'PR Labels'
'on':
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
jobs:
  pr_labels:
    name: 'ğŸ­ Verify'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'ğŸ· Verify PR has a valid label'
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'breaking change, bug, documentation, enhancement, refactor, performance, new feature, maintenance, ci, dependencies, question'
          disable-reviews: true
