name: Stale
'on':
  schedule:
    -
      cron: '0 8 * * *'
  workflow_dispatch: null
jobs:
  stale:
    name: 'üßπ Clean up stale issues and PRs'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'üöÄ Run stale'
        uses: actions/stale@v9
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          days-before-stale: 180
          days-before-close: 7
          remove-stale-when-updated: true
          stale-issue-label: stale
          exempt-issue-labels: 'no stale,help wanted'
          stale-issue-message: "There hasn't been any activity on this issue recently, so we clean up some of the older and inactive issues. Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by leaving a comment üëç. This issue has now been marked as stale and will be closed if no further activity occurs. Thanks!\n"
          stale-pr-label: stale
          exempt-pr-labels: 'no stale'
          stale-pr-message: "There hasn't been any activity on this pull request recently. This pull request has been automatically marked as stale because of that and will be closed if no further activity occurs within 7 days. Thank you for your contributions.\n"
